branches:
  only:
    - /^master.*$/
    - /^release.*$/

language: java

filter_secrets: false
jdk: oraclejdk8
sudo: required
install: skip
dist: precise

before_script:
  - ./sbin/trusona-env.sh

script:
  - ./gradlew clean build

deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script:
    ./sbin/ci-publisher.sh $TRAVIS_BRANCH $TRAVIS_EVENT_TYPE
